import Head from 'next/head';
import Image from 'next/image';

/**
 * La page d'accueil
 * @return {NextPage} La page d'accueil
 */
export default function Home() {
	return (
		<div className={'py-0 px-16'}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={'flex min-h-screen px-16 py-0 flex-1 flex-col justify-center items-center'}>
				<h1 className={/* styles.title */'m-0 leading-tight text-6xl text-center'}>
					Welcome to <a
						className={'text-sky-600 no-underline hover:underline focus:underline active:underline'}
						href="https://nextjs.org"
					>
						Next.js!
					</a>
				</h1>

				<p className={/* styles.description */'mx-16 my-0 text-center text-2xl leading-6'}>
					Get started by editing{' '}
					<code className={/* styles.code */'bg-zinc-50 rounded p-3 text-base'}>pages/index.js</code>
				</p>

				<div className={/* styles.grid */'flex items-center justify-center flex-wrap max-w-[800px]'}>
					<a href="https://nextjs.org/docs" className={/* styles.card */`m-4 p-6 text-left text-inherit no-underline 
													border border-solid border-neutral-200 rounded-[10px] 
													
													transition-colors max-w-[300px] 
													hover:border-blue-500 hover:text-blue-500 
													focus:border-blue-500 focus:text-blue-500 
													active:border-blue-500 active:text-blue-500`}>
						<h2 className={'mt-0 mr-0 mb-5 ml-0 text-2xl'}>Documentation &rarr;</h2>
						<p className={'m-0 text-xl leading-normal'}>Find in-depth information about Next.js features and API.</p>
					</a>

					<a href="https://nextjs.org/learn" className={/* styles.card */`m-4 p-6 text-left text-inherit no-underline 
													border border-solid border-neutral-200 rounded-[10px] 
													
													transition-colors max-w-[300px] 
													hover:border-blue-500 hover:text-blue-500 
													focus:border-blue-500 focus:text-blue-500 
													active:border-blue-500 active:text-blue-500`}>
						<h2 className={'mt-0 mr-0 mb-5 ml-0 text-2xl'}>Learn &rarr;</h2>
						<p className={'m-0 text-xl leading-normal'}>Learn about Next.js in an interactive course with quizzes!</p>
					</a>

					<a
						href="https://github.com/vercel/next.js/tree/canary/examples"
						className={/* styles.card */`m-4 p-6 text-left text-inherit no-underline 
													border border-solid border-neutral-200 rounded-[10px] 
													
													transition-colors max-w-[300px] 
													hover:border-blue-500 hover:text-blue-500 
													focus:border-blue-500 focus:text-blue-500 
													active:border-blue-500 active:text-blue-500`}
					>
						<h2 className={'mt-0 mr-0 mb-5 ml-0 text-2xl'}>Examples &rarr;</h2>
						<p className={'m-0 text-xl leading-normal'}>Discover and deploy boilerplate example Next.js projects.</p>
					</a>

					<a
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={/* styles.card */`m-4 p-6 text-left text-inherit no-underline 
													border border-solid border-neutral-200 rounded-[10px] 
													
													transition-colors max-w-[300px] 
													hover:border-blue-500 hover:text-blue-500 
													focus:border-blue-500 focus:text-blue-500 
													active:border-blue-500 active:text-blue-500`}
					>
						<h2 className={'mt-0 mr-0 mb-5 ml-0 text-2xl'}>Deploy &rarr;</h2>
						<p className={'m-0 text-xl leading-normal'}>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</a>
				</div>
			</main>

			<footer className={/* styles.footer */'flex flex-1 px-8 py-0 border border-solid border-neutral-200 justify-center items-center'}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
					className='flex justify-center items-center grow'
				>
					Powered by{' '}
					<span className={'h-4 ml-2'}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
